kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4

networking:
  apiServerAddress: "127.0.0.1" # 默认 "127.0.0.1" ，如果你需要在外部访问则需要修改为 "Node IP"
  apiServerPort: 6443
  kubeProxyMode: "iptables" # 默认 "iptables", Kind 中开启 IPVS 可能会导致错误 https://github.com/kubernetes-sigs/kind/issues/2326
  podSubnet: "10.244.0.0/16"
  serviceSubnet: "10.96.0.0/12"
  disableDefaultCNI: false # 默认 "false" ，如果你需要自己部署 CNI 则设为 "true"

containerdConfigPatches: # 根据需要指定镜像仓库
  # 下面列举了一些镜像加速地址。
  # - Docker 中国区官方镜像加速：https://registry.docker-cn.com
  # - 网易镜像加速：http://hub-mirror.c.163.com
  # - 中国科技大学镜像加速：https://docker.mirrors.ustc.edu.cn
  # - 腾讯云镜像加速：https://mirror.ccs.tencentyun.com
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."docker.io"]
    endpoint = ["https://mirror.ccs.tencentyun.com"]
nodes:
- role: control-plane
  extraPortMappings:
      # 只在一台节点配置 nodePort 端口映射既可，
      # 因为当指定 nodePort 后 k8s 集群每台节点都会暴露 nodePort ，访问任意一个既可路由到 ClusterIP Service。
  - containerPort: 30880 # containerPort（kind 节点想要映射到主机的 nodePort 端口）默认 30000-32767
    hostPort: 30880      # hostPort（宿主机端口）默认 0-65535 （注意不可重复）
    protocol: tcp # 默认 "tcp"
    listenAddress: "0.0.0.0" # 默认 "0.0.0.0"
  - containerPort: 30080
    hostPort: 80
    protocol: tcp
    listenAddress: "0.0.0.0"
  image: kindest/node:v1.21.14@sha256:9d9eb5fb26b4fbc0c6d95fa8c790414f9750dd583f5d7cee45d92e8c26670aa1  # images 发布地址 https://github.com/kubernetes-sigs/kind/releases
- role: worker
  image: kindest/node:v1.21.14@sha256:9d9eb5fb26b4fbc0c6d95fa8c790414f9750dd583f5d7cee45d92e8c26670aa1