servers:
  - name: server1
    os: kalilinux/rolling:2023.1.0
    network:
      - 192.168.56.10:private_network:add_hosts
      #- 192.168.63.20:public_network
    port_forward:
      - 8121:22:ssh
default_config:
  default_region: local
  default_cpu: 2
  default_mem: 2048
  default_network_mode: private_network
  default_os: ubuntu/jammy64
  boot_timeout: 300
  # 挂载目录选项
  default_synced_folder:
    create: true
    owner: vagrant
    group: vagrant
    mount_options: ["dmode=755", "fmode=644"]
    type: virtualbox -# virtualbox、NFS 或 rsync
  # 设置启动顺序
  boot_order: ["disk", "dvd", "none"]
      # 自定义密钥
  ssh_pub_keys:
    local_key:
      - "#{Dir.home}/.ssh/id_rsa.pub"
