servers:
  - name: server1
    os: ubuntu/lunar64:20230301.0.0
    cpu: 2
    mem: 2048
    region: dev
    provision_shell:
      - "bootstrap.sh:arg1 arg2 arg3"
      - "bootstrap2.sh"
    network:
      - 192.168.56.10:private_network:add_hosts
      - 192.168.63.20:public_network
    port_forward:
      - 8121:22:ssh
      - 8980:80:name
    mount:
      - ./sharedir1:/vagrant1
      - ./sharedir2:/vagrant2
    disk:
      - disk1:100GB:primary
      - disk2:10GB
    dvd:
      - dvd1:/home/admin/Storage/6.ISO/WePE64_V2.2.iso
  - name: server2
    port_forward:
      - 8122:22:ssh
    network:
      - 192.168.56.20:private_network:add_hosts

default_config:
  default_region: local
  default_cpu: 1
  default_mem: 1024
  default_network_mode: private_network
  default_os: ubuntu/jammy64
    # 挂载目录选项
  default_synced_folder:
    create: true
    owner: vagrant
    group: vagrant
    mount_options: ["dmode=755", "fmode=644"]
    type: virtualbox -# virtualbox、NFS 或 rsync
  # 设置启动顺序
  boot_order: ["disk", "dvd", "none"]
      # 自定义密钥
  ssh_pub_keys:
    remote_key:
      - "https://raw.githubusercontent.com/hashicorp/vagrant/main/keys/vagrant.pub"
    local_key:
      - "#{Dir.home}/.ssh/id_rsa.pub"
    content_key:
      - "test-key"
      - "demo-key"
