---
- hosts: all
  become: true
  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        update_cache: true
    - name: Copy Nginx config file
      copy:
        src: /vagrant/nginx.conf
        dest: /etc/nginx/nginx.conf
    - name: Restart Nginx
      service:
        name: nginx
        state: restarted