apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: my-configmap
    literals:
      - foo=bar1
      - baz=qux1
  - name: my-configmap2
    behavior: replace # 显示指定行为为替换
    literals:
      - foo=bar2
      - baz=qux2
generatorOptions:
  disableNameSuffixHash: true #关闭哈希后缀
