version: '3'
services:
  web:
    image: nginx:stable
    volumes:
      - ./mountPath/src:/usr/share/nginx/html
      - ./mountPath/nginx:/etc/nginx/
    ports:
      - "8080:80"
    healthcheck:
        test: curl --fail http://localhost || exit 1
        interval: 60s
        retries: 5
        start_period: 20s
        timeout: 10s

