---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
type: Opaque
stringData:
  api-token: fbeP1_p15NvXiTVdrI8PPgwfU54Pc92yUq2wGdOJ
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: issuer-account-key
# type: Opaque
# data:
#   privateKey: bXktcHJpdmlsZS1rZXkK
# # echo "my-private-key" | base64
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cloudflare-issuer
spec:
  acme:
    email: song.jinfeng@outlook.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-key
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token