apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: my-hostpath-sc
  hostPath:
    path: /data/my-pv
    type: DirectoryOrCreate