servers:
  - name: control
    network:
      - 192.168.56.100:private_network:add_hosts
    port_forward:
      - 8685:22:ssh
    provision_shell_inline:
      - "sudo timedatectl set-timezone Asia/Shanghai"
      - "sudo sed -e 's|^mirrorlist=|#mirrorlist=|g' \
        -e 's|^#baseurl=http://mirror.centos.org/centos|baseurl=https://mirrors.tuna.tsinghua.edu.cn/centos|g' \
        -i.bak \
        /etc/yum.repos.d/CentOS-*.repo && sudo sed -i 's/nameserver .*/nameserver 8.8.8.8/' /etc/resolv.conf && sudo yum install epel-release -y && sudo yum install ansible -y"      
  - name: node1
    network:
      - 192.168.56.10:private_network:add_hosts
    port_forward:
      - 8686:22:ssh       
    provision_shell_inline:
      - "sudo timedatectl set-timezone Asia/Shanghai"
  - name: node2
    network:
      - 192.168.56.20:private_network:add_hosts
    port_forward:
      - 8687:22:ssh       
    provision_shell_inline:
      - "sudo timedatectl set-timezone Asia/Shanghai"
  - name: node3
    network:
      - 192.168.56.30:private_network:add_hosts
    port_forward:
      - 8688:22:ssh       
    provision_shell_inline:
      - "sudo timedatectl set-timezone Asia/Shanghai"
default_config:
  default_region: lab.local
  default_cpu: 1
  default_mem: 1024
  default_network_mode: private_network
  default_os: centos/7:2004.01
  boot_timeout: 300
  default_gui: false
  # 设置启动顺序
  boot_order: ["disk", "dvd", "none"]
  # 挂载目录选项
  default_synced_folder:
    create: true
    owner: vagrant
    group: vagrant
    mount_options: ["dmode=755", "fmode=644"]
    type: virtualbox # virtualbox、NFS 或 rsync
  # 自定义密钥
  ssh_pub_keys:
    local_key:
      - "#{Dir.home}/.ssh/id_rsa.pub"
